export type User = { id: string; email: string; displayName: string };
export type Account = { id: string; name: string; type: string; openingBalance: number; currentBalance: number; institutionName?: string };
export type Category = { id: string; name: string; type: string; color?: string; icon?: string; archived: boolean };
export type Transaction = { id: string; type: string; amount: number; transactionDate: string; merchant?: string; note?: string; paymentMethod?: string; tags?: string; account: Account; category?: Category };
export type Budget = { id: string; month: number; year: number; amount: number; alertThresholdPercent: number; category: Category };
export type Goal = { id: string; name: string; targetAmount: number; currentAmount: number; targetDate?: string; color?: string; icon?: string; status: string; linkedAccount?: Account };
export type RecurringTransaction = { id: string; title: string; type: string; amount: number; frequency: string; startDate: string; endDate?: string; nextRunDate: string; autoCreateTransaction: boolean; paused: boolean; account?: Account; category?: Category };
export type AuthResponse = { accessToken: string; refreshToken: string; user: User };
export type ForgotPasswordResponse = { message: string; resetUrl?: string | null };
export type AuditEvent = { id: string; eventType: string; payload: string; createdAt: string };
export type DashboardAlert = { level: string; title: string; body: string };
export type Dashboard = {
  monthIncome: number;
  monthExpense: number;
  netBalance: number;
  trackedBalance: number;
  topExpenseCategory: string;
  overBudgetCount: number;
  savingsProgressPercent: number;
  recentTransactions: Transaction[];
  upcomingRecurring: RecurringTransaction[];
  dueTodayRecurring: RecurringTransaction[];
  overdueRecurring: RecurringTransaction[];
  goals: Goal[];
  budgets: Array<{ id: string; category: string; amount: number; spent: number; percent: number; thresholdReached: boolean; alertLevel?: string }>;
  budgetAlerts: DashboardAlert[];
  categorySpend: Array<{ name: string; value: number }>;
  incomeExpenseTrend: Array<{ label: string; income: number; expense: number }>;
  accounts: Account[];
  accountBreakdown: Array<{ id: string; name: string; type: string; value: number }>;
};
export type ReportTransaction = { date: string; type: string; merchant: string; account: string; category: string; amount: number; paymentMethod: string; note: string };
export type ReportResponse = {
  summary: { income: number; expense: number; net: number; transactionCount: number; rangeLabel: string };
  filters: { type?: string | null; accountId?: string | null; categoryId?: string | null };
  categorySpend: Array<{ name: string; value: number }>;
  incomeVsExpense: Array<{ label: string; income: number; expense: number }>;
  accountBalanceTrend: Array<{ name: string; value: number }>;
  savingsProgress: Array<{ name: string; currentAmount: number; targetAmount: number }>;
  topCategories: string[];
  transactions: ReportTransaction[];
};
